version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:U6w$UE_X-F$B7hC@db:5432/postgres
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: U6w$UE_X-F$B7hC
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
