version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL=postgresql://postgres.jkvdwxwwafrscenjgkck:dsfjohnyboy123@aws-0-us-east-2.pooler.supabase.com:5432/postgres
      API_KEY_SID: SK48345ee0fb8b9862eb47adb9b1be877d
      API_KEY_SECRET: aNnmWOafvYZCrgGavRDiEyvly28c5fOf
      TWILIO_ACCOUNT_SID: SK48345ee0fb8b9862eb47adb9b1be877d
      TWILIO_AUTH_TOKEN: aNnmWOafvYZCrgGavRDiEyvly28c5fOf
      TWILIO_VERIFY_SID: VAc1c5e91108c4ac6b139170a382b0ab6c"
      SQUARE_ACCESS_TOKEN: EAAAl2oiaTQ80E45r9_qyynWLybZgaZt6ByCEAW0GYW323N4JubZQAFGFel_y_-Z
      SQUARE_APPLICATION_ID: sandbox-sq0idb-1dkCceTofcOyHAVjWsn-pQ
      SQUARE_ENVIRONMENT: sandbox
      SUPABASE_URL: https://supabase.com/dashboard/project/jkvdwxwwafrscenjgkck
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprdmR3eHd3YWZyc2Nlbmpna2NrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTc0ODgyMiwiZXhwIjoyMDY3MzI0ODIyfQ.YcxexCcB7Xid1Pn07K21gbCduXUPhHCk7o5zvYEDcn0
