// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkvdwxwwafrscenjgkck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprdmR3eHd3YWZyc2Nlbmpna2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDg4MjIsImV4cCI6MjA2NzMyNDgyMn0.6YTjxok18m6xWQa5djhBl3oJ6l3a9IeR4fI8ijYjnrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});